language: node_js
sodu: required
services:
  - docker
before-install:
  - docker build -t hariomsingh/docker-react -f Dockerfile.dev .

script:
  - docker run hariomsingh/docker-react npm run test -- --coverage -